### PR TITLE
Oauth login with test page

### PR DESCRIPTION
**Pull request by grepsedawk**
If you guys could code review then pull into master that would be amazing! @eshadatta @ekate

### CODE REVIEW

**Comment by eshadatta** [comment]
@pachonk ,

Thanks for the PR. We had a few comments and a question.

Is this initial PR just for your local dev environment? If so, this is fine. If this is towards a final production app, @ekate and I are both a little confused because we don't see the library login gem in the Gemfile. In the video that you had posted on Slack, it looked like you were using the login gem. We will need to use the login gem for production code. Also, this is an api app, so we won't be handling any native views except for whatever login page is generated by the login gem.

Thanks.

**Comment by grepsedawk** [comment]
@eshadatta I'm a little confused. The repository linked to me was https://github.com/NYULibraries/login which isn't a gem, so I can't include it in my gem file. Is there another "login gem" that you would like me to implement directly into this application?
The way I ended up running this is 2 different apps running on my same machine that talk to each other.

**Comment by grepsedawk** [comment]
As far as the single view goes, it's made to be removed ASAP. The only reason it was added was to compete the task "Create a test page" on Pivotal Tracker.

**Comment by ekate** [comment]
@pachonk you are supposed to use this gem in your application
https://github.com/NYULibraries/omniauth-nyulibraries
to connect to library login application, which in turn in your local environment can connect to doorkeeper but in prod will connect to shib

**Comment by grepsedawk** [comment]
Ah okay, I was unaware of this gem and the issue in pivotal provided me with the login repository. That being said, my repo has a very similar strategy to this gem: https://github.com/NYULibraries/dlts-middleware-authz/blob/oauth-login/lib/doorkeeper.rb vs https://github.com/NYULibraries/omniauth-nyulibraries/blob/master/lib/omniauth/strategies/nyulibraries.rb (there's just a little more content in the gem).
I will switch to the gem after I have completed the API.

Thanks.

**Comment by ekate** [comment]
@pachonk you may find this useful. It is provided in the login repo:
https://github.com/NYULibraries/login/blob/633a343748f0fdfe215565cbe20263a5d2352c79/GETTING_STARTED.md

**Comment by grepsedawk** [comment]
Ah, very helpful. Most of that I found in my own discoveries, but I'm switching to the gem because it'll increase the maintainability of the authz repo. Closing this PR until it's switched over.

**Pull request closed without merging**
