### PR TITLE
Items redirect to the end_service.uri with params

### PR DESCRIPTION
**Pull request by grepsedawk**
Depends on #9 (depends on #4)

### CODE REVIEW

**Comment by ekate** [comment]
@pachonk I think you are doing it correctly in general. 
A question about this method:
https://github.com/NYULibraries/dlts-middleware-authz/blob/item-url/app/controllers/items_controller.rb#L5
I think we should use handle as an item external id, e.g. when you get to the fetch method you will be passed item handle, something like 2333.1/899y6t676. You can find the item using handle, not token and then redirect  to the appropriate end service and pass the same handle parameter+ session token
I think we probably does not need item token at all

**Comment by grepsedawk** [comment]
@ekate I was trying to follow your original schema, so just to get some clarity:
Are you saying remove the token column from Item altogether?

**Comment by ekate** [comment]
@pachonk yes, I know that token was part of the initial model. I just think we can remove it as part of this PR

**Comment by grepsedawk** [comment]
@ekate sounds good, I just wanted to make sure I was clear on what you were asking. Thanks!

**Comment by grepsedawk** [comment]
Ah, forgot to say @ekate moved to handle.

**Comment by ekate** [comment]
@jgpawletko I think it does what we expect it to do. If you don't have any comments I will merge it

**Comment by jgpawletko** [comment]
Hi @ekate ,
this is OK to merge.

**Comment by grepsedawk** [comment]
This depends on #9 to be pulled in prior to this being merged.

**Pull request merged**
